<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Reply extends Model
{
    use HasFactory;


    protected $with = ['reply_replies'];

    protected $fillable = ['body', 'user_id', 'post_id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($reply) {
            return $reply->user_id = auth()->id();
        });

    }

    public function reply_replies()
    {
        return $this->hasMany(ReplyReply::class);
    }

    public function reply_likes()
    {
        return $this->hasMany(ReplyLike::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}
