<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ReplyReply extends Model
{
    use HasFactory;

    protected $fillable = ['body', 'user_id', 'reply_id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($reply_reply) {
            return $reply_reply->user_id = auth()->id();
        });

    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}
